local M = {}

function M.hl(c)
	return {
		["goPointerOperator"] = { fg = c.yellow_candle },
		-- ["goParen"] = { fg = c.yellow_candle },
		["goPackage"] = { fg = c.grey_simple },
		["goImport"] = { fg = c.grey_simple },
		["goImportString"] = { fg = c.grey_simple },
		["goLabel"] = { fg = c.yellow_sunglow_dim },
		["goVar"] = { fg = c.yellow_coral },
		["goDeclaration"] = { fg = c.red_coral },
		["goConditional"] = { fg = c.white_dust0 },
		["goFunctionReturn"] = { fg = c.white_dust2 },
		["goFunction"] = { fg = c.white_dust2 },
		["goField"] = { fg = c.red_coral },
		["goFunctionCall"] = { fg = c.red_coral },
		["goConst"] = { fg = c.grey_corporate },
		["goStatement"] = { fg = c.blue_deepsky },
		["goType"] = { fg = c.grey_smokey },
		["goExtraType"] = { fg = c.yellow_sunglow_dim },
		["goPredefinedIdentifiers"] = { fg = c.white_dust2 },
		["goTypeName"] = { fg = c.shocking_orange },
		["goBlock"] = { fg = c.red_coral },
		["goSingleDecl"] = { fg = c.yellow_candle },
		["goDeclType"] = { fg = c.white_dust3 },
		["goGenerate"] = { fg = c.shocking_orange },
		["goGenerateVariables"] = { fg = c.yellow_candle },
		["goSpecialString"] = { fg = c.white_dust3 },
		["goBuiltins"] = { fg = c.blue_deepsky },
		["goBuildDirectives"] = { fg = c.blue_deepsky },
		["goParamName"] = { fg = c.grape },
		["goParamType"] = { fg = c.grape },
		["goBuildKeyword"] = { fg = c.grape },
		["goOperator"] = { fg = c.white_dust2 },
		["goTypeConstructor"] = { fg = c.grape },
		["goReceiverVar"] = { fg = c.white_dust2 },
		["goReceiver"] = { fg = c.grape },
		["goSignedInts"] = { fg = c.white_dust3 },
		["goUnsignedInts"] = { fg = c.white_dust3 },
		["goFormatSpecifier"] = { fg = c.grey_smokey },
		["goString"] = { fg = c.grey_corporate },
		["goEscapeC"] = { fg = c.grey_corporate },
		["@keyword.return.go"] = { fg = c.green_shadow },
		["@function.builtin.go"] = { fg = c.shocking_orange },
		["@type.builtin.go"] = { fg = c.grey_corporate },
		["@type.go"] = { fg = c.white_dust2 },
		["@variable.go"] = { fg = c.grey_simple },
		["@property.go"] = { fg = c.grey_corporate },
		["@operator.go"] = { fg = c.dark_grey },
		["@function.method.go"] = { fg = c.white_dust2 },
		["@function.method.call.go"] = { fg = c.grey_smokey },
		["@variable.parameter.go"] = { fg = c.grey_smokey },
		["@punctuation.bracket.go"] = { fg = c.dark_grey },
	}
end

return M
