local M = {}

function M.hl(c)
	return {
		["goPointerOperator"] = { fg = c.yellow_candle },
		["goParen"] = { fg = c.yellow_candle },
		["goPackage"] = { fg = c.white_dust2 },
		["goImport"] = { fg = c.white_dust2 },
		["goImportString"] = { fg = c.grey_davy },
		["goLabel"] = { fg = c.yellow_sunglow_dim },
		["goRepeat"] = { fg = c.white_dust2 },
		["goVar"] = { fg = c.green_meadow2 },
		["goDeclaration"] = { fg = c.red_orange },
		["goConditional"] = { fg = c.white_dust0 },
		["goFunctionReturn"] = { fg = c.white_dust2 },
		["goFunction"] = { fg = c.white_dust2 },
		["goField"] = { fg = c.red_orange },
		["goFunctionCall"] = { fg = c.red_orange },
		["goConst"] = { fg = c.grey_corporate },
		["goStatement"] = { fg = c.blue_deepsky },
		["goType"] = { fg = c.white_dust2 },
		["goExtraType"] = { fg = c.yellow_sunglow_dim },
		["goPredefinedIdentifiers"] = { fg = c.white_dust2 },
		["goTypeName"] = { fg = c.shocking_orange },
		["goBlock"] = { fg = c.grey_davy },
		["goSingleDecl"] = { fg = c.yellow_candle },
		["goDeclType"] = { fg = c.white_dust3 },
		["goGenerate"] = { fg = c.shocking_orange },
		["goGenerateVariables"] = { fg = c.yellow_candle },
		["goSpecialString"] = { fg = c.white_dust3 },
		["goBuiltins"] = { fg = c.white_dust2 },
		["goBuildDirectives"] = { fg = c.blue_deepsky },
		["goParamName"] = { fg = c.grape },
		["goParamType"] = { fg = c.grape },
		["goBuildKeyword"] = { fg = c.grape },
		["goOperator"] = { fg = c.white_dust2 },
		["goTypeConstructor"] = { fg = c.grape },
		["goReceiverVar"] = { fg = c.white_dust2 },
		["goReceiver"] = { fg = c.grape },
		["goSignedInts"] = { fg = c.white_dust3 },
		["goUnsignedInts"] = { fg = c.white_dust3 },
		["goFormatSpecifier"] = { fg = c.grey_smokey },
		["goString"] = { fg = c.grey_corporate },
		["goDecimalInt"] = { fg = c.white_dust },
		["goEscapeC"] = { fg = c.grey_corporate },
	}
end

return M
