local M = {}

function M.hl(c)
	return {
		["goPointerOperator"] = { fg = c.yellow_candle },
		["goPackage"] = { fg = c.grey_simple },
		["goImport"] = { fg = c.grey_simple },
		["goImportString"] = { fg = c.grey_simple },
		["goLabel"] = { fg = c.yellow_sunglow_dim },
		["goVar"] = { fg = c.yellow_coral },
		["goDeclaration"] = { fg = c.red_coral },
		["goConditional"] = { fg = c.white_dust0 },
		["goFunctionReturn"] = { fg = c.white_dust2 },
		["goFunction"] = { fg = c.white_dust2 },
		["goField"] = { fg = c.red_coral },
		["goFunctionCall"] = { fg = c.red_coral },
		["goConst"] = { fg = c.grey_corporate },
		["goStatement"] = { fg = c.blue_deepsky },
		["goType"] = { fg = c.grey_smokey },
		["goExtraType"] = { fg = c.yellow_sunglow_dim },
		["goPredefinedIdentifiers"] = { fg = c.white_dust2 },
		["goTypeName"] = { fg = c.shocking_orange },
		["goBlock"] = { fg = c.red_coral },
		["goSingleDecl"] = { fg = c.yellow_candle },
		["goDeclType"] = { fg = c.white_dust3 },
		["goGenerate"] = { fg = c.shocking_orange },
		["goGenerateVariables"] = { fg = c.yellow_candle },
		["goSpecialString"] = { fg = c.white_dust3 },
		["goBuiltins"] = { fg = c.blue_deepsky },
		["goBuildDirectives"] = { fg = c.blue_deepsky },
		["goParamName"] = { fg = c.grape },
		["goParamType"] = { fg = c.grape },
		["goBuildKeyword"] = { fg = c.grape },
		["goOperator"] = { fg = c.white_dust2 },
		["goTypeConstructor"] = { fg = c.grape },
		["goReceiverVar"] = { fg = c.white_dust2 },
		["goReceiver"] = { fg = c.grape },
		["goSignedInts"] = { fg = c.white_dust3 },
		["goUnsignedInts"] = { fg = c.white_dust3 },
		["goFormatSpecifier"] = { fg = c.grey_smokey },
		["goString"] = { fg = c.grey_corporate },
		["goEscapeC"] = { fg = c.grey_corporate },
		["@keyword.return.go"] = { fg = c.neutral_20 },
		["@keyword.type.go"] = { fg = c.neutral_20 },
		["@function.builtin.go"] = { fg = c.crimson_40 },
		["@type.builtin.go"] = { fg = c.neutral_30 },
		["@type.go"] = { fg = c.grey_simple },
		["@function.go"] = { fg = c.neutral_15 },
		["@variable.go"] = { fg = c.neutral_20 },
		["@type.definition.go"] = { fg = c.neutral_15 },
		["@constant.go"] = { fg = c.crimson_40 },
		["@property.go"] = { fg = c.grey_corporate },
		["@operator.go"] = { fg = c.dark_grey },
		["@function.method.go"] = { fg = c.white_dust2 },
		["@keyword.coroutine.go"] = { fg = c.blue_deepsky },
		["@function.method.call.go"] = { fg = c.grey_smokey },
		["@function.call.go"] = { fg = c.neutral_15 },
		["@variable.parameter.go"] = { fg = c.neutral_20 },
		["@punctuation.bracket.go"] = { fg = c.dark_grey },

		["@keyword.repeat.go"] = { fg = c.neutral_15 },
		["@keyword.conditional.go"] = { fg = c.green_dull },
		["@keyword.function.go"] = { fg = c.grey_davy },
		["@keyword.go"] = { fg = c.white_dust3 },
		["@namespace.go"] = { bold = true },
		["@module.go"] = { fg = c.neutral_20 },
		["@string.go"] = { fg = c.neutral_20 },
		["@constant.builtin.go"] = { fg = c.grey_davy },
	}
end

return M
